### ISSUE TITLE
zookeeper使用Acl权限认证，dubbo注册不上！

### ISSUE THREAD

**Issue by h602140** [alibaba/dubbo-spring-boot-starter#29]
Caused by: com.alibaba.dubbo.rpc.RpcException: Failed to register dubbo://10.0.73.219:20901/org.jsfund.weal.core.service.UserService?anyhost=true&application=jsfundService&default.loadbalance=roundrobin&default.threadpool=fixed&default.threads=10&default.timeout=25000&dispatcher=all&dubbo=2.5.3&interface=org.jsfund.weal.core.service.UserService&methods=queryByCondition,selectByPrimaryKey,insertSelective,isValidate,updateByPrimaryKey,deleteByPrimaryKey,insert,updateByPrimaryKeySelective,updateByPhoneSelective&owner=service&pid=13840&retries=0&revision=1.0&side=provider&threadpool=cached&threads=5000&timeout=30000&timestamp=1509607712570&version=1.0 to zookeeper zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=jsfundService&dubbo=2.5.3&interface=com.alibaba.dubbo.registry.RegistryService&owner=service&pid=13840&timeout=25000&timestamp=1509607712570, cause: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /dubbo/org.jsfund.weal.core.service.UserService
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:102)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:130)
	... 23 common frames omitted
Caused by: org.I0Itec.zkclient.exception.ZkException: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /dubbo/org.jsfund.weal.core.service.UserService
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:68)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1000)
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:527)
	at org.I0Itec.zkclient.ZkClient.createPersistent(ZkClient.java:293)
	at org.I0Itec.zkclient.ZkClient.createPersistent(ZkClient.java:270)
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.createPersistent(ZkclientZookeeperClient.java:43)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:44)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:39)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:39)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:100)
	... 24 common frames omitted
Caused by: org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /dubbo/org.jsfund.weal.core.service.UserService
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:113)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.I0Itec.zkclient.ZkConnection.create(ZkConnection.java:99)
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:530)
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:527)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:990)

**Comment by xionghuiCoder** [comment]
hi,请参考下改答案：https://www.zhihu.com/question/45720203/answer/140188334
