### ISSUE TITLE
@Reference(check=false)配置不生效

### ISSUE THREAD

**Issue by zhangqijia** [alibaba/dubbo-spring-boot-starter#57]
注册中心检查关闭不了，项目启动不起来。

> 
Caused by: com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. Tried 3 times of the providers [zookeeper.server:2181] (1/1) from the registry zookeeper.server:2181 on the consumer 10.240.112.57 using the dubbo version 2.6.0. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://zookeeper.server:2181/com.alibaba.dubbo.registry.RegistryService?application=up-service-appreciation&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.6.0&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=8932&reconnect=false&remote.timestamp=1517300464123&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1517300464123&unsubscribe.1.callback=false, cause: Waiting server-side response timeout by scan timer. start time: 2018-01-30 16:21:24.396, end time: 2018-01-30 16:21:34.397, client elapsed: 50 ms, server elapsed: 9951 ms, timeout: 10000 ms, request: Request [id=4, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://10.240.112.57/com.alibaba.dubbo.registry.RegistryService?application=up-service-appreciation&callbacks=10000&connect.timeout=10000&dubbo=2.6.0&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=8932&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1517300464123&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@58fbd02e], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=1492897838, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 10.240.112.57:0 -> zookeeper.server/192.168.3.3:2181
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:232)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
	at com.alibaba.dubbo.common.bytecode.proxy0.subscribe(proxy0.java)
	at com.alibaba.dubbo.registry.dubbo.DubboRegistry.doSubscribe(DubboRegistry.java:138)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:201)
	... 31 common frames omitted
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2018-01-30 16:21:24.396, end time: 2018-01-30 16:21:34.397, client elapsed: 50 ms, server elapsed: 9951 ms, timeout: 10000 ms, request: Request [id=4, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://10.240.112.57/com.alibaba.dubbo.registry.RegistryService?application=up-service-appreciation&callbacks=10000&connect.timeout=10000&dubbo=2.6.0&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=8932&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1517300464123&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@58fbd02e], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=1492897838, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 10.240.112.57:0 -> zookeeper.server/192.168.3.3:2181
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:216)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:137)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:111)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:142)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:73)
	at com.alibaba.dubbo.spring.boot.listener.ConsumerInvokeStaticsFilter.invoke(ConsumerInvokeStaticsFilter.java:32)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:47)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:52)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	... 37 common frames omitted

2018-01-30 16:21:34.517 ERROR org.springframework.boot.SpringApplication Line:771 - Application startup failed

**Comment by ijaychang** [comment]
see https://github.com/apache/incubator-dubbo/issues/195
